[package]
name = "notify"
version = "1.2.3"
authors = [
  "Félix Saparelli <me@passcod.name>",
  "Antti Keränen <detegr@gmail.com>",
  "Jorge Israel Peña <jorge.israel.p@gmail.com>",
  "Michael Maurizi <mmaurizi@azavea.com>",
]

description = "Cross-platform filesystem notification library"
homepage = "https://github.com/passcod/rsnotify"
repository = "https://github.com/passcod/rsnotify"

readme = "README.md"
license = "CC0-1.0"
keywords = [
  "events",
  "filesystem",
  "notify",
  "watch",
]

[dependencies]
bitflags = "*"
libc = "*"
log = "*"
time = "*"
walker = "^1.0.0"

[target.x86_64-unknown-linux-gnu.dependencies.inotify]
version = "^0.1"

[features]
poll = []
